# Dict of bingo tasks
task_list = {
    1: "Most cumulative beer brought during all task completions (Not applicable for kill count tiles or long xp gain tiles. Think of this as beer held while completing a task)",
    2: "Receive a non-prayer scroll purple unique from Chambers of Xeric (Buckler, DHCB, Dinh's, Ancestral, Dragon Claws, Elder Maul, Kodai, Twisted Bow, Kit, Dust, Pet) (ONYX DOES NOT COUNT)",
    3: "Obtain an Enhanced Crystal Weapon Seed",
    4: "Achieve 5,000,000 Woodcutting XP AND obtain a Fox Whistle",
    5: "Obtain all pieces to complete a Voidwaker",
    6: "Obtain a Warped sceptre",
    7: "Achieve 125,000 xp/hr for a minimum of 60 minutes while mining",
    8: "Obtain a Dark Bow",
    9: "Obtain an Ash covered tome from Petrified Pete's Ore Shop",
    10: "Obtain one of three Dragon-ish Visages (Skeletal, Wyvern, or Draconic)",
    11: "Last the longest, while still killing the Corrupted Hunleff (Must loot chest after)",
    12: "Receive a purple unique from Theatre of Blood (Avernic defender hilt, Justicar, Rapier, Sanguinesti, Scythe, Kit, Dust, Pet)",
    13: "Alch the purple you received (one time use)",
    14: "Complete Chambers solo in under 17 minutes, trio under 14:30, or any other team size under 12:30.",
    15: "Receive an imbued heart, dust battlestaff, mist battlestaff, or eternal gem from a Superior",
    16: "Obtain a drop from the Mega-rare table from a master clue",
    17: "Obtain an Abyssal Lantern and Abyssal Needle",
    18: "Obtain an Occult Necklace",
    19: "Obtain all of the wilderness rings",
    20: "Complete a Grandmaster quest",
    21: "Earn a Fire cape before anyone else. (Time starts when I post this message. First team to finish a fire cape, then submit a successful fire cape completion screenshot, with a timestamp, to Foki Bot wins. YOU MUST HAVE A TIMESTAMP FROM ONE OF THE CODEWORD PLUGINS WITH UTC TIME SHOWING",
    22: "Score a goal in gnomeball against an opposing bingo team. (Since you're technically on the same team against gnomes, the team who scores first, or best out of three will get points. There can be multiple rounds if you'd like. The winning criteria should be agreed upon by the teams participating and posted in the chatbox for my reference. Good luck.",
    23: "Obtain a Revenant Weapon (Viggora's Chainmace, Craw's Bow, or Thammaron's Sceptre)",
    24: "Receive a good purple unique from Tombs of Amascut (Masori, Fang, Shadow, Pet)",
    25: 'Obtain the following: Bandos Chestplate, Armadyl Chainskirt, Zamorak Spear, Armadyl Crossbow, Zaryte Vambraces. Then wear this outfit and screenshot saying "I am the God this dungeon was named after." (have other weapon in inventory while not wearing)',
    26: "Obtain a Slepey Tablet and any Nightmare Unique (Staff, Inquisitor, Orb, Pet, Jar, Egg)",
    27: "Obtain a Hydra Claw or Hydra Leather",
    28: "Successfully bake a Wild Pie. Ironman style. (Gather all ingredients, and successfully process.)",
    29: "Obtain a Pharaoh's Sceptre from Pyramid Plunder",
    30: "Obtain a unique from Zalcano (Crystal tool seed, Zalcano shard, pet, onyx)",
    31: 'Least deaths wins at ToB. Nominate your Champion and "PK" opposing teams while still successfully completing ToB. Points go to the team whos member has the least deaths. There will be 2 raid groups of 3 - one from each team. In the event of a tie, least-death tied teams receive 5 points.',
    32: "Achieve the highest level invocation Tombs of Amascut completion in any scale.",
    33: "Obtain a Sigil, Jar, or Pet from Corp",
    34: "Obtain any vestige from one of the Desert Treasure II bosses",
    35: "Obtain an Eternal Glory",
    36: "Kill 10 different quest bosses (NOT within Nightmare Zone)",
    37: "Receive exactly an 84,000 experience drop. Must be one single xp drop. ",
    38: "Complete a heavy ballista (Like get the drops, not buying them off the G.E. like a disgusting normie)",
    39: "Create an Amulet of Torture, Ironman style",
    40: "Obtain Dragon limbs.",
    41: "Earn an Infernal cape before anyone else. (Completion with the earliest UTC time earns points for their team)",
    42: "Purchase a Bounty hunter ornament kit (One of the (cr) ones) (cannot be boosted/friends/clan/etc.)",
    43: "Obtain a crystal from Cerberus (Eternal, Pegasian, Primordial)",
    44: "Obtain a non-head unique from Vorkath (Dragonbone necklace, Jar, pet, either visage) ((asking about wrath talisman loses your team 1 point))",
    45: "Obtain Bryophyta's Essence",
    46: "Obtain a Nex Unique (Hilt, Vambs, Torva, Horn, Pet) (I will allow vambs if you already got them from the God of the Dungeon tile)",
    47: "Kill Giant Mole 500 times",
    48: "Obtain all four rings from Dagannoth Kings",
    49: "Purchase 10000+ sharks from minnows in a single transaction",
    50: "Catch a Lucky Impling",
    51: "Win a game of Connect-Four against another team's member",
    52: 'Earn the title: "of a Thousand Hunts". Catch 1000 Salamanders, 1000 Chins, 1000 Implings, and 1000 Herbiboar.',
    53: 'Have 3 people from your team earn an Infernal cape (if you got a kc during the "earn a cape before anyone else" tile, I will count that too)',
    54: "Obtain a fang and a visage from Zulrah",
    55: "Obtain a Granite thing from Grotesque Guardians (except dust)",
    56: "Obtain a double item chest from Barrows, or finish a full set for one brother",
    57: "Receive a Dragon Full Helm as a drop",
    58: "Obtain a Sarachnis cudgel",
    59: "Receive a Blood Shard as a drop (Thieving or Killing Vyrewatch)",
    60: "Obtain an Earth Warrior Champion's Scroll",
    61: "Kill one of anything, then use these dropped resources to earn the most xp compared to any team. (e.g. if you kill a goblin and get bones, you could bury for 4.5xp and submit that. Document the process/steps with timestamps)",
    62: "Best fashionscape (Foki is judge) (Submit all screenshots anonymously from team captain with no identifiable info)",
    63: "Make your Torva bloody. (Kill all 4 awakened bosses. if you already have blood torva, screenshot new kcs of each boss.)",
    64: "Kill the King Black Dragon without wearing or equipping anything",
    65: "Kill all five God Wars bosses in a single inventory without banking or leaving the God Wars Dungeon",
    66: "Obtain an Abyssal Whip",
    67: "Obtain a master wand from the mage training arena",
    68: "Win a game of Castle Wars against another competing team",
    69: "Obtain a Dragon Warhammer",
    70: "Obtain full Virtus",
    71: "Obtain a Skotizo unique (claw, pet, onyx, Jar) ",
    72: "Turn Amy into a Sellout. Buy one of everything from the Mahogany Homes Reward Shop",
    73: "Obtain an Unsired",
    74: "Obtain a Trident of the seas, and a Kraken tentacle",
    75: "Achieve the most consecutive LMS wins. (Screenshots of each win with kc is required)",
    76: "Obtain a Venator Shard",
    77: "Complete a deathless, 3-man ToB with a maximum of 1 person from each bingo team",
    78: "Obtain a Kalphite Queen uniqe (Tattered head, Dragon pickaxe, pet, jar, dragon chainbody)",
    79: "Obtain a Black mask",
    80: "Create a sword in Giant's Foundry with a score of 69",
    81: "Purchase the full Brimhaven Agility Arena Graceful recolour",
    82: "Most gp earned in 1 hour on a fresh lvl 3 FTP ironman - final screenshot must include time played and be less than 60 mintues",
    83: "Kill Duke Sucellus with the least valuable setup",
    84: "Complete a sled run in Goblin Village with a time of 0:50 or less",
    85: "Obtain a bunch of stuff from Chaos Archeologist. (Rcb, Fedora, Odium Shard, Malediction Shard)",
    86: "Achieve Diamond time for the Earnest the Chicken quest speedrun",
    87: "Equip the highest combined defense and attack bonus out of any team while on Entrana. (Will add up the two highest + bonuses)",
    88: "Kill the bunny in Priffdinas",
    89: "Obtain a full set of Chaos Druid robes",
    90: "Achieve a Hallowed Sepulchre (all 5 floors) time of 6:20 or better",
    91: "Obtain a Clue in a Bottle of every type simultaneously (all five tiers)",
    999: "TEST TASK",
}

bonus_tasks = {
    92: "BONUS: Get a skilling pet",
    93: "BONUS: Get a boss pet",
    94: "BONUS: Get a 99",
    95: "BONUS: PK over 100m. This is not cumulative. One PK. They cannot be in clan, not in deathmatch, not a friend. Just a good ol' fashioned wildy PK.",
    96: "BONUS: Get Sasa to say \"I love you\"",
}

# Dict of bingo task point values
task_points = {
    1: 5,
    2: 2,
    3: 3,
    4: 2,
    5: 3,
    6: 1,
    7: 1,
    8: 1,
    9: 1,
    10: 3,
    11: 5,
    12: 2,
    13: 1,
    14: 2,
    15: 3,
    16: 3,
    17: 2,
    18: 1,
    19: 2,
    20: 2,
    21: 5,
    22: 1,
    23: 2,
    24: 2,
    25: 3,
    26: 2,
    27: 2,
    28: 1,
    29: 1,
    30: 2,
    31: 5,
    32: 3,
    33: 3,
    34: 3,
    35: 2,
    36: 1,
    37: 1,
    38: 2,
    39: 1,
    40: 2,
    41: 5,
    42: 3,
    43: 1,
    44: 2,
    45: 1,
    46: 2,
    47: 1,
    48: 1,
    49: 2,
    50: 1,
    51: 5,
    52: 3,
    53: 5,
    54: 2,
    55: 1,
    56: 2,
    57: 3,
    58: 1,
    59: 1,
    60: 1,
    61: 5,
    62: 3,
    63: 3,
    64: 1,
    65: 2,
    66: 1,
    67: 1,
    68: 5,
    69: 3,
    70: 3,
    71: 1,
    72: 2,
    73: 1,
    74: 1,
    75: 5,
    76: 1,
    77: 3,
    78: 1,
    79: 1,
    80: 1,
    81: 1,
    82: 5,
    83: 3,
    84: 1,
    85: 1,
    86: 1,
    87: 3,
    88: 1,
    89: 1,
    90: 1,
    91: 1,
    92: 1,
    93: 1,
    94: 1,
    95: 1,
    96: 1,
    999: 999,  # test task
}

# Gives user profiles custom titles
player_titles_dict = {
    1: "Formidable",
    2: "Green",
    3: "Monumental",
    4: "Smelly",
    5: "Courageous",
    6: "Mean Bean",
    7: "Crafty",
    8: "Humble",
    9: "Terrible",
    10: "Vile",
    11: "Despicable",
    12: "Sinister",
    13: "Malevolent",
    14: "Nasty",
    15: "Wretched",
    16: "Gruesome",
    17: "Cruel",
    18: "Abominable",
    19: "Diabolical",
    20: "Fiendish",
    21: "Wise",
    22: "Fearless",
    23: "Radiant",
    24: "Agile",
    25: "Mysterious",
    26: "Charming",
    27: "Dynamic",
    28: "Tranquil",
    29: "Bold",
    30: "Melodious",
    31: "Mystical",
    32: "Daring",
    33: "Luminous",
    34: "Swift",
    35: "Enigmatic",
    36: "Charismatic",
    37: "Spirited",
    38: "Serene",
    39: "Audacious",
    40: "Harmonious",
    41: "Sweaty",
    42: "Fine",
    43: "Bold",
    44: "Snake",
    45: "Strategic",
    46: "Tactical",
    47: "Agile",
    48: "Skilled",
    49: "Adaptable",
    50: "Precise",
    51: "Quick-thinking",
    52: "Persistent",
    53: "Competitive",
    54: "Resourceful",
    55: "Alert",
    56: "Focused",
    57: "Clever",
    58: "Tenacious",
    59: "Efficient",
    60: "Coordinated",
    61: "Versatile",
    62: "Inventive",
    63: "Adept",
    64: "Intuitive",
    65: "Spoon",
    66: "Unit",
    67: "Fiesty",
    68: "Pet",
    69: "Floppy",
    70: "Slayer",
    71: "Titilizer",
    72: "Artistic",
    73: "Stabby",
    74: "Thicc",
    75: "Glizzy",
    76: "Bankstander",
    77: "Awakened",
    78: "Fluffy",
    79: "Bad",
    80: "Squirty",
    81: "Wumbo",
    82: "Foreigner",
    83: "Prince",
    84: "Spicy",
    85: "Dying",
    86: "Swell",
    87: "Spoiled",
    88: "Normie",
    89: "Tryhard",
    90: "Cringe",
    91: "Rizzler",
    92: "Miner",
    93: "Chopper",
    94: "Farmer",
    95: "Hunter",
    96: "Crafter",
    97: "Thief",
    98: "Chef",
    99: "Smith",
    100: "Archer",
    101: "Saucy",
    102: "Sarcastic",
    103: "Witty",
}

# Bot submission responses
submission_responses = {
    1: "DID YOU REMEMBER YOUR CODEWORD?",
    2: "REALLY? THIS IS YOUR SUBMISSION? ARE YOU SURE?",
    3: "YOU'RE THE FIRST PERSON TO SUBMIT THIS! PROBABLY. MAYBE.",
    4: "ABOUT TIME.",
    5: "FINALLY!",
    6: "ARE YOU WAITING FOR A TIP? GO AWAY.",
    7: "CONGRATS [USER] FOR YOUR DROP/ACHIEVEMENT/THING!",
    8: "FOKI ALREADY HAS ONE OF THESE, SO...",
    9: "TOOK YA LONG ENOUGH!",
    10: "FUCK YOU DJ",
}
