# Dict of bingo tasks
task_list = {
1: "[5 points] Most cumulative beer brought during all task completions (Not applicable for kill count tiles or long XP gain tiles. Think of this as beer held while completing a task)",
2: "[2 points] Receive a non-prayer scroll purple unique from Chambers of Xeric (Buckler, DHCB, Dinh's, Ancestral, Dragon Claws, Elder Maul, Kodai, Twisted Bow, Kit, Dust, Pet) (ONYX DOES NOT COUNT)",
3: "[3 points] Obtain an Enhanced Crystal Weapon Seed",
4: "[2 points] Achieve 5,000,000 Woodcutting XP AND obtain a Fox Whistle",
5: "[3 points] Obtain all pieces to complete a Voidwaker",
6: "[1 point] Obtain a Warped sceptre",
7: "[1 point] Achieve 125,000 XP/hr for a minimum of 60 minutes while mining",
8: "[1 point] Obtain a Dark Bow",
9: "[1 point] Obtain an Ash covered tome from Petrified Pete's Ore Shop",
10: "[3 points] Obtain one of three Dragon-ish Visages (Skeletal, Wyvern, or Draconic)",
11: "[5 points] Last the longest, while still killing the Corrupted Hunleff (Must loot chest after)",
12: "[2 points] Receive a purple unique from Theatre of Blood (Avernic defender hilt, Justiciar, Rapier, Sanguinesti, Scythe, Kit, Dust, Pet)",
13: "[1 point] Alch the purple you received (one time use)",
14: "[2 points] Complete Chambers solo in under 17 minutes, trio under 14:30, or any other team size under 12:30.",
15: "[3 points] Receive an imbued heart, dust battlestaff, mist battlestaff, or eternal gem from a Superior",
16: "[3 points] Obtain a drop from the Mega-rare table from a master clue",
17: "[2 points] Obtain an Abyssal Lantern and Abyssal Needle",
18: "[1 point] Obtain an Occult Necklace",
19: "[2 points] Obtain all of the wilderness rings",
20: "[2 points] Complete a Grandmaster quest",
21: "[5 points] Earn a Fire cape before anyone else",
22: "[1 point] Score a goal in gnomeball against an opposing bingo team",
23: "[2 points] Obtain a Revenant Weapon (Viggora's Chainmace, Craw's Bow, or Thammaron's Sceptre)",
24: "[2 points] Receive a good purple unique from Tombs of Amascut (Masori, Fang, Shadow, Pet)",
25: "[3 points] Obtain the following: Bandos Chestplate, Armadyl Chainskirt, Zamorak Spear, Armadyl Crossbow, Zaryte Vambraces. Then wear this outfit and screenshot saying \"I am the God this dungeon was named after.\" (have other weapon in inventory while not wearing)",
26: "[2 points] Obtain a Slepey Tabley and any Nightmare Unique (Staff, Inquisitor, Orb, Pet, Jar, Egg)",
27: "[2 points] Obtain a Hydra Claw or Hydra Leather",
28: "[1 point] Successfully bake a Wild Pie. Ironman style. (Gather all ingredients, and successful process.)",
29: "[1 point] Obtain a Pharaoh's Sceptre from Pyramid Plunder",
30: "[2 points] Obtain a unique from Zalcano (Crystal tool seed, Zalcano shard, pet, onyx)",
31: "[5 points] Least deaths wins. Nominate your Champion, \"PK\" opposing teams while completing ToB. One point goes to the team whose member has the least deaths. There will be 2 raid groups of 3 - one from each team.",
32: "[3 points] Achieve the highest level invocation Tombs of Amascut completion in any scale",
33: "[3 points] Obtain a Sigil, Jar, or Pet from Corp",
34: "[3 points] Obtain any vestige from one of the Desert Treasure II bosses",
35: "[2 points] Obtain an Eternal Glory",
36: "[1 point] Kill 10 different quest bosses (NOT within Nightmare Zone)",
37: "[1 point] Receive an 84,000 thieving experience drop",
38: "[2 points] Complete a heavy ballista (Like get the drops, not buying them off the G.E. like a disgusting normie)",
39: "[1 point] Create an Amulet of Torture, Ironman style",
40: "[2 points] Obtain Dragon limbs",
41: "[5 points] Earn an Infernal cape before anyone else",
42: "[3 points] Achieve the most valuable Bounty Hunter PK (cannot be boosted/friends/clan/etc.)",
43: "[1 point] Obtain a crystal from Cerberus (Eternal, Pegasian, Primordial)",
44: "[2 points] Obtain a non-head unique from Vorkath (Dragonbone necklace, Jar, pet, either visage) ((asking about wrath talisman loses your team 1 point))",
45: "[1 point] Obtain Bryophyta's Essence",
46: "[2 points] Obtain a Nex Unique (Hilt, Vambs, Torva, Horn, Pet) (I will allow vambs if you already got them from the God of the Dungeon tile)",
47: "[1 point] Kill Giant Mole 500 times",
48: "[1 point] Obtain all four rings from Dagannoth Kings",
49: "[2 points] Purchase 10000+ sharks from minnows in a single transaction",
50: "[1 point] Catch a Lucky Impling",
51: "[5 points] Win a game of Connect-Four against another team's member",
52: "[3 points] Earn the title: \"of a Thousand Hunts\". Catch 1000 Salamanders, 1000 Chins, 1000 Implings, and 1000 Herbiboar.",
53: "[5 points] Have 3 people from your team earn an Infernal cape (if you got a kc during the \"earn a cape before anyone else\" tile, I will count that too)",
54: "[2 points] Obtain a fang and a visage from Zulrah",
55: "[1 point] Obtain a Granite thing from Grotesque Guardians (except dust)",
56: "[2 points] Obtain a double item chest from Barrows, or finish a full set for one brother",
57: "[3 points] Receive a Dragon Full Helm as a drop",
58: "[1 point] Obtain a Sarachnis cudgel",
59: "[1 point] Receive a Blood Shard as a drop (Thieving or Killing Vyrewatch)",
60: "[1 point] Obtain an Earth Warrior Champion's Scroll",
61: "[5 points] Achieve the largest XP drop out of any other team (Must show up as a single XP drop to count)",
62: "[3 points] Best fashionscape (Foki is judge) (Submit all screenshots anonymously from team captain with no identifiable info)",
63: "[3 points] Make your Torva bloody. (Kill all 4 awakened bosses. if you already have blood torva, screenshot new kcs of each boss.)",
64: "[1 point] Kill the King Black Dragon without wearing or equipping anything",
65: "[2 points] Kill all five God Wars bosses in a single inventory without banking or leaving the God Wars Dungeon",
66: "[1 point] Obtain an Abyssal Whip",
67: "[1 points] Obtain a master wand from the mage training arena",
68: "[5 points] Win a game of Castle Wars against another competing team",
69: "[3 points] Obtain a Dragon Warhammer",
70: "[3 points] Obtain full Virtus",
71: "[1 point] Obtain a Skotizo unique (claw, pet, onyx, Jar) ",
72: "[2 points] Turn Amy into a Sellout. Buy one of everything from the Mahogany Homes Reward Shop",
73: "[1 point] Obtain an Unsired",
74: "[1 point] Obtain a Trident of the seas, and a Kraken tentacle",
75: "[5 points] Achieve the most consecutive LMS wins. (Screenshots of each win with kc is required)",
76: "[1 point] Obtain a Venator Shard",
77: "[3 points] Complete a deathless, 3-man ToB with a maximum of 1 person from each bingo team",
78: "[1 point] Obtain a Kalphite Queen unique (Tattered head, Dragon pickaxe, pet, jar, dragon chainbody)",
79: "[1 point] Obtain a Black mask",
80: "[1 point] Create a sword in Giant's Foundry with a score of 69",
81: "[1 point] Purchase the full Brimhaven Agility Arena Graceful recolour",
82: "[5 points] Most gp earned in 1 hour on a fresh lvl 3 FTP ironman - final screenshot must include time played and be less than 60 mintues",
83: "[3 points] Kill Duke Sucellus with the least valuable setup",
84: "[1 point] Complete a sled run in Goblin Village with a time of 0:50 or less",
85: "[1 point] Obtain a bunch of stuff from Chaos Archeologist. (Rcb, Fedora, Odium Shard, Malediction Shard)",
86: "[1 point] Achieve Diamond time for the Earnest the Chicken quest speedrun",
87: "[3 points] Equip the highest combined defense and attack bonus out of any team while on Entrana. (Will add up the two highest + bonuses)",
88: "[1 point] Kill the bunny in Priffdinas",
89: "[1 point] Obtain a full set of Chaos Druid robes",
90: "[1 point] Achieve a Hallowed Sepulchre (all 5 floors) time of 6:20 or better",
91: "[1 point] Obtain a Clue in a Bottle of every type simultaneously (all five tiers)",
92: "[1 point] BONUS: Get a skilling pet",
93: "[1 point] BONUS: Get a boss pet",
94: "[1 point] BONUS: Get a 99",
95: "[1 point] BONUS: PK over 100m to someone not in clan, not in deathmatch. Just a good ol fashioned wildy PK.",
96: "[1 point] BONUS: Get Sasa to say \"I love you\"",
999: "TEST TASK"
}

# Dict of bingo task point values
task_points = {
    1: 5,
    2: 2,
    3: 3,
    4: 2,
    5: 3,
    6: 1,
    7: 1,
    8: 1,
    9: 1,
    10: 3,
    11: 5,
    12: 2,
    13: 1,
    14: 2,
    15: 3,
    16: 3,
    17: 2,
    18: 1,
    19: 2,
    20: 2,
    21: 5,
    22: 1,
    23: 2,
    24: 2,
    25: 3,
    26: 2,
    27: 2,
    28: 1,
    29: 1,
    30: 2,
    31: 5,
    32: 3,
    33: 3,
    34: 3,
    35: 2,
    36: 1,
    37: 1,
    38: 2,
    39: 1,
    40: 2,
    41: 5,
    42: 3,
    43: 1,
    44: 2,
    45: 1,
    46: 2,
    47: 1,
    48: 1,
    49: 2,
    50: 1,
    51: 5,
    52: 3,
    53: 5,
    54: 2,
    55: 1,
    56: 2,
    57: 3,
    58: 1,
    59: 1,
    60: 1,
    61: 5,
    62: 3,
    63: 3,
    64: 1,
    65: 2,
    66: 1,
    67: 1,
    68: 5,
    69: 3,
    70: 3,
    71: 1,
    72: 2,
    73: 1,
    74: 1,
    75: 5,
    76: 1,
    77: 3,
    78: 1,
    79: 1,
    80: 1,
    81: 1,
    82: 5,
    83: 3,
    84: 1,
    85: 1,
    86: 1,
    87: 3,
    88: 1,
    89: 1,
    90: 1,
    91: 1,
    92: 1,
    93: 1,
    94: 1,
    95: 1,
    96: 1,
    999: 999 # test task
}

# Gives user profiles custom titles
player_titles_dict = {
    1: "Formidable",
    2: "Green",
    3: "Monumental",
    4: "Smelly",
    5: "Courageous",
    6: "Mean Bean",
    7: "Crafty",
    8: "Humble",
    9: "Terrible",
    10: "Vile",
    11: "Despicable",
    12: "Sinister",
    13: "Malevolent",
    14: "Nasty",
    15: "Wretched",
    16: "Gruesome",
    17: "Cruel",
    18: "Abominable",
    19: "Diabolical",
    20: "Fiendish",
    21: "Wise",
    22: "Fearless",
    23: "Radiant",
    24: "Agile",
    25: "Mysterious",
    26: "Charming",
    27: "Dynamic",
    28: "Tranquil",
    29: "Bold",
    30: "Melodious",
    31: "Mystical",
    32: "Daring",
    33: "Luminous",
    34: "Swift",
    35: "Enigmatic",
    36: "Charismatic",
    37: "Spirited",
    38: "Serene",
    39: "Audacious",
    40: "Harmonious",
    41: "Sweaty",
    42: "Fine",
    43: "Bold",
    44: "Snake",
    45: "Strategic",
    46: "Tactical",
    47: "Agile",
    48: "Skilled",
    49: "Adaptable",
    50: "Precise",
    51: "Quick-thinking",
    52: "Persistent",
    53: "Competitive",
    54: "Resourceful",
    55: "Alert",
    56: "Focused",
    57: "Clever",
    58: "Tenacious",
    59: "Efficient",
    60: "Coordinated",
    61: "Versatile",
    62: "Inventive",
    63: "Adept",
    64: "Intuitive",
    65: "Spoon",
    66: "Unit",
    67: "Fiesty",
    68: "Pet",
    69: "Floppy",
    70: "Slayer",
    71: "Titilizer",
    72: "Artistic",
    73: "Stabby",
    74: "Thicc",
    75: "Glizzy",
    76: "Bankstander",
    77: "Awakened",
    78: "Fluffy",
    79: "Bad",
    80: "Squirty",
    81: "Wumbo",
    82: "Foreigner",
    83: "Prince",
    84: "Spicy",
    85: "Dying",
    86: "Swell",
    87: "Spoiled",
    88: "Normie",
    89: "Tryhard",
    90: "Cringe",
    91: "Rizzler",
    92: "Miner",
    93: "Chopper",
    94: "Farmer",
    95: "Hunter",
    96: "Crafter",
    97: "Thief",
    98: "Chef",
    99: "Smith",
    100: "Archer",
    101: "Saucy",
    102: "Sarcastic",
    103: "Witty",
}

# Bot submission responses
submission_responses = {
    1: "DID YOU REMEMBER YOUR CODEWORD?",
    2: "REALLY? THIS IS YOUR SUBMISSION? ARE YOU SURE?",
    3: "YOU'RE THE FIRST PERSON TO SUBMIT THIS! PROBABLY. MAYBE.",
    4: "ABOUT TIME.",
    5: "FINALLY!",
    6: "ARE YOU WAITING FOR A TIP? GO AWAY.",
    7: "CONGRATS [USER] FOR YOUR DROP/ACHIEVEMENT/THING!",
    8: "FOKI ALREADY HAS ONE OF THESE, SO...",
    9: "TOOK YA LONG ENOUGH!",
    10: "FUCK YOU DJ",
}