CREATE DATABASE IF NOT EXISTS `battle_bingo`;
USE `battle_bingo`;

DROP TABLE IF EXISTS `tasks`;
DROP TABLE IF EXISTS `team_hokumpoke`;
DROP TABLE IF EXISTS `team_hokumpoke_board_state`;
DROP TABLE IF EXISTS `team_seczey`;
DROP TABLE IF EXISTS `team_seczey_board_state`;
DROP TABLE IF EXISTS `team_kyanize`;
DROP TABLE IF EXISTS `team_kyanize_board_state`;
DROP TABLE IF EXISTS `team_prime`;
DROP TABLE IF EXISTS `team_prime_board_state`;
DROP TABLE IF EXISTS `team_blepe`;
DROP TABLE IF EXISTS `team_blepe_board_state`;
DROP TABLE IF EXISTS `team_unphased`;
DROP TABLE IF EXISTS `team_unphased_board_state`;

CREATE TABLE `team_hokumpoke` (
	`player_id` INT AUTO_INCREMENT NOT NULL,
    `player_name` VARCHAR(20) NOT NULL,
    `tasks_completed` INT DEFAULT 0,
    PRIMARY KEY(`player_id`)
);

CREATE TABLE `team_hokumpoke_board_state` (
	`task_id` INT AUTO_INCREMENT NOT NULL,
    `task_completion` BOOLEAN,
    `completed_by` VARCHAR(20) DEFAULT "",
    `completed_on` DATETIME,
    PRIMARY KEY(`task_id`)
);

INSERT INTO `team_hokumpoke_board_state` VALUES 
(1, 0, "", null),
(2, 0, "", null),
(3, 0, "", null),
(4, 0, "", null),
(5, 0, "", null),
(6, 0, "", null),
(7, 0, "", null),
(8, 0, "", null),
(9, 0, "", null),
(10, 0, "", null),
(11, 0, "", null),
(12, 0, "", null),
(13, 0, "", null),
(14, 0, "", null),
(15, 0, "", null),
(16, 0, "", null),
(17, 0, "", null),
(18, 0, "", null),
(19, 0, "", null),
(20, 0, "", null),
(21, 0, "", null),
(22, 0, "", null),
(23, 0, "", null),
(24, 0, "", null),
(25, 0, "", null),
(26, 0, "", null),
(27, 0, "", null),
(28, 0, "", null),
(29, 0, "", null),
(30, 0, "", null),
(31, 0, "", null),
(32, 0, "", null),
(33, 0, "", null),
(34, 0, "", null),
(35, 0, "", null),
(36, 0, "", null),
(37, 0, "", null),
(38, 0, "", null),
(39, 0, "", null),
(40, 0, "", null),
(41, 0, "", null),
(42, 0, "", null),
(43, 0, "", null),
(44, 0, "", null),
(45, 0, "", null),
(46, 0, "", null),
(47, 0, "", null),
(48, 0, "", null),
(49, 0, "", null),
(50, 0, "", null),
(51, 0, "", null),
(52, 0, "", null),
(53, 0, "", null),
(54, 0, "", null),
(55, 0, "", null),
(56, 0, "", null),
(57, 0, "", null),
(58, 0, "", null),
(59, 0, "", null),
(60, 0, "", null),
(61, 0, "", null),
(62, 0, "", null),
(63, 0, "", null),
(64, 0, "", null),
(65, 0, "", null),
(66, 0, "", null),
(67, 0, "", null),
(68, 0, "", null),
(69, 0, "", null),
(70, 0, "", null),
(71, 0, "", null),
(72, 0, "", null),
(73, 0, "", null),
(74, 0, "", null),
(75, 0, "", null),
(76, 0, "", null),
(77, 0, "", null),
(78, 0, "", null),
(79, 0, "", null),
(80, 0, "", null),
(81, 0, "", null),
(82, 0, "", null),
(83, 0, "", null),
(84, 0, "", null),
(85, 0, "", null),
(86, 0, "", null),
(87, 0, "", null),
(88, 0, "", null),
(89, 0, "", null),
(90, 0, "", null),
(91, 0, "", null),
(92, 0, "", null),
(93, 0, "", null),
(94, 0, "", null),
(95, 0, "", null),
(96, 0, "", null);

CREATE TABLE `team_seczey` (
	`player_id` INT AUTO_INCREMENT NOT NULL,
    `player_name` VARCHAR(20) NOT NULL,
    `tasks_completed` INT,
    PRIMARY KEY(`player_id`)
);

CREATE TABLE `team_seczey_board_state` (
	`task_id` INT AUTO_INCREMENT NOT NULL,
    `task_completion` BOOLEAN,
    `completed_by` VARCHAR(20) DEFAULT "",
    `completed_on` DATETIME,
    PRIMARY KEY(`task_id`)
);

INSERT INTO `team_seczey_board_state` VALUES 
(1, 0, "", null),
(2, 0, "", null),
(3, 0, "", null),
(4, 0, "", null),
(5, 0, "", null),
(6, 0, "", null),
(7, 0, "", null),
(8, 0, "", null),
(9, 0, "", null),
(10, 0, "", null),
(11, 0, "", null),
(12, 0, "", null),
(13, 0, "", null),
(14, 0, "", null),
(15, 0, "", null),
(16, 0, "", null),
(17, 0, "", null),
(18, 0, "", null),
(19, 0, "", null),
(20, 0, "", null),
(21, 0, "", null),
(22, 0, "", null),
(23, 0, "", null),
(24, 0, "", null),
(25, 0, "", null),
(26, 0, "", null),
(27, 0, "", null),
(28, 0, "", null),
(29, 0, "", null),
(30, 0, "", null),
(31, 0, "", null),
(32, 0, "", null),
(33, 0, "", null),
(34, 0, "", null),
(35, 0, "", null),
(36, 0, "", null),
(37, 0, "", null),
(38, 0, "", null),
(39, 0, "", null),
(40, 0, "", null),
(41, 0, "", null),
(42, 0, "", null),
(43, 0, "", null),
(44, 0, "", null),
(45, 0, "", null),
(46, 0, "", null),
(47, 0, "", null),
(48, 0, "", null),
(49, 0, "", null),
(50, 0, "", null),
(51, 0, "", null),
(52, 0, "", null),
(53, 0, "", null),
(54, 0, "", null),
(55, 0, "", null),
(56, 0, "", null),
(57, 0, "", null),
(58, 0, "", null),
(59, 0, "", null),
(60, 0, "", null),
(61, 0, "", null),
(62, 0, "", null),
(63, 0, "", null),
(64, 0, "", null),
(65, 0, "", null),
(66, 0, "", null),
(67, 0, "", null),
(68, 0, "", null),
(69, 0, "", null),
(70, 0, "", null),
(71, 0, "", null),
(72, 0, "", null),
(73, 0, "", null),
(74, 0, "", null),
(75, 0, "", null),
(76, 0, "", null),
(77, 0, "", null),
(78, 0, "", null),
(79, 0, "", null),
(80, 0, "", null),
(81, 0, "", null),
(82, 0, "", null),
(83, 0, "", null),
(84, 0, "", null),
(85, 0, "", null),
(86, 0, "", null),
(87, 0, "", null),
(88, 0, "", null),
(89, 0, "", null),
(90, 0, "", null),
(91, 0, "", null),
(92, 0, "", null),
(93, 0, "", null),
(94, 0, "", null),
(95, 0, "", null),
(96, 0, "", null);


CREATE TABLE `team_kyanize` (
	`player_id` INT AUTO_INCREMENT NOT NULL,
    `player_name` VARCHAR(20) NOT NULL,
    `tasks_completed` INT,
    PRIMARY KEY(`player_id`)
);

CREATE TABLE `team_kyanize_board_state` (
	`task_id` INT AUTO_INCREMENT NOT NULL,
    `task_completion` BOOLEAN,
    `completed_by` VARCHAR(20) DEFAULT "",
    `completed_on` DATETIME,
    PRIMARY KEY(`task_id`)
);

INSERT INTO `team_kyanize_board_state` VALUES 
(1, 0, "", null),
(2, 0, "", null),
(3, 0, "", null),
(4, 0, "", null),
(5, 0, "", null),
(6, 0, "", null),
(7, 0, "", null),
(8, 0, "", null),
(9, 0, "", null),
(10, 0, "", null),
(11, 0, "", null),
(12, 0, "", null),
(13, 0, "", null),
(14, 0, "", null),
(15, 0, "", null),
(16, 0, "", null),
(17, 0, "", null),
(18, 0, "", null),
(19, 0, "", null),
(20, 0, "", null),
(21, 0, "", null),
(22, 0, "", null),
(23, 0, "", null),
(24, 0, "", null),
(25, 0, "", null),
(26, 0, "", null),
(27, 0, "", null),
(28, 0, "", null),
(29, 0, "", null),
(30, 0, "", null),
(31, 0, "", null),
(32, 0, "", null),
(33, 0, "", null),
(34, 0, "", null),
(35, 0, "", null),
(36, 0, "", null),
(37, 0, "", null),
(38, 0, "", null),
(39, 0, "", null),
(40, 0, "", null),
(41, 0, "", null),
(42, 0, "", null),
(43, 0, "", null),
(44, 0, "", null),
(45, 0, "", null),
(46, 0, "", null),
(47, 0, "", null),
(48, 0, "", null),
(49, 0, "", null),
(50, 0, "", null),
(51, 0, "", null),
(52, 0, "", null),
(53, 0, "", null),
(54, 0, "", null),
(55, 0, "", null),
(56, 0, "", null),
(57, 0, "", null),
(58, 0, "", null),
(59, 0, "", null),
(60, 0, "", null),
(61, 0, "", null),
(62, 0, "", null),
(63, 0, "", null),
(64, 0, "", null),
(65, 0, "", null),
(66, 0, "", null),
(67, 0, "", null),
(68, 0, "", null),
(69, 0, "", null),
(70, 0, "", null),
(71, 0, "", null),
(72, 0, "", null),
(73, 0, "", null),
(74, 0, "", null),
(75, 0, "", null),
(76, 0, "", null),
(77, 0, "", null),
(78, 0, "", null),
(79, 0, "", null),
(80, 0, "", null),
(81, 0, "", null),
(82, 0, "", null),
(83, 0, "", null),
(84, 0, "", null),
(85, 0, "", null),
(86, 0, "", null),
(87, 0, "", null),
(88, 0, "", null),
(89, 0, "", null),
(90, 0, "", null),
(91, 0, "", null),
(92, 0, "", null),
(93, 0, "", null),
(94, 0, "", null),
(95, 0, "", null),
(96, 0, "", null);


CREATE TABLE `team_prime` (
	`player_id` INT AUTO_INCREMENT NOT NULL,
    `player_name` VARCHAR(20) NOT NULL,
    `tasks_completed` INT,
    PRIMARY KEY(`player_id`)
);

CREATE TABLE `team_prime_board_state` (
	`task_id` INT AUTO_INCREMENT NOT NULL,
    `task_completion` BOOLEAN,
    `completed_by` VARCHAR(20) DEFAULT "",
    `completed_on` DATETIME,
    PRIMARY KEY(`task_id`)
);

INSERT INTO `team_prime_board_state` VALUES 
(1, 0, "", null),
(2, 0, "", null),
(3, 0, "", null),
(4, 0, "", null),
(5, 0, "", null),
(6, 0, "", null),
(7, 0, "", null),
(8, 0, "", null),
(9, 0, "", null),
(10, 0, "", null),
(11, 0, "", null),
(12, 0, "", null),
(13, 0, "", null),
(14, 0, "", null),
(15, 0, "", null),
(16, 0, "", null),
(17, 0, "", null),
(18, 0, "", null),
(19, 0, "", null),
(20, 0, "", null),
(21, 0, "", null),
(22, 0, "", null),
(23, 0, "", null),
(24, 0, "", null),
(25, 0, "", null),
(26, 0, "", null),
(27, 0, "", null),
(28, 0, "", null),
(29, 0, "", null),
(30, 0, "", null),
(31, 0, "", null),
(32, 0, "", null),
(33, 0, "", null),
(34, 0, "", null),
(35, 0, "", null),
(36, 0, "", null),
(37, 0, "", null),
(38, 0, "", null),
(39, 0, "", null),
(40, 0, "", null),
(41, 0, "", null),
(42, 0, "", null),
(43, 0, "", null),
(44, 0, "", null),
(45, 0, "", null),
(46, 0, "", null),
(47, 0, "", null),
(48, 0, "", null),
(49, 0, "", null),
(50, 0, "", null),
(51, 0, "", null),
(52, 0, "", null),
(53, 0, "", null),
(54, 0, "", null),
(55, 0, "", null),
(56, 0, "", null),
(57, 0, "", null),
(58, 0, "", null),
(59, 0, "", null),
(60, 0, "", null),
(61, 0, "", null),
(62, 0, "", null),
(63, 0, "", null),
(64, 0, "", null),
(65, 0, "", null),
(66, 0, "", null),
(67, 0, "", null),
(68, 0, "", null),
(69, 0, "", null),
(70, 0, "", null),
(71, 0, "", null),
(72, 0, "", null),
(73, 0, "", null),
(74, 0, "", null),
(75, 0, "", null),
(76, 0, "", null),
(77, 0, "", null),
(78, 0, "", null),
(79, 0, "", null),
(80, 0, "", null),
(81, 0, "", null),
(82, 0, "", null),
(83, 0, "", null),
(84, 0, "", null),
(85, 0, "", null),
(86, 0, "", null),
(87, 0, "", null),
(88, 0, "", null),
(89, 0, "", null),
(90, 0, "", null),
(91, 0, "", null),
(92, 0, "", null),
(93, 0, "", null),
(94, 0, "", null),
(95, 0, "", null),
(96, 0, "", null);


CREATE TABLE `team_blepe` (
	`player_id` INT AUTO_INCREMENT NOT NULL,
    `player_name` VARCHAR(20) NOT NULL,
    `tasks_completed` INT,
    PRIMARY KEY(`player_id`)
);

CREATE TABLE `team_blepe_board_state` (
	`task_id` INT AUTO_INCREMENT NOT NULL,
    `task_completion` BOOLEAN,
    `completed_by` VARCHAR(20) DEFAULT "",
    `completed_on` DATETIME,
    PRIMARY KEY(`task_id`)
);

INSERT INTO `team_blepe_board_state` VALUES 
(1, 0, "", null),
(2, 0, "", null),
(3, 0, "", null),
(4, 0, "", null),
(5, 0, "", null),
(6, 0, "", null),
(7, 0, "", null),
(8, 0, "", null),
(9, 0, "", null),
(10, 0, "", null),
(11, 0, "", null),
(12, 0, "", null),
(13, 0, "", null),
(14, 0, "", null),
(15, 0, "", null),
(16, 0, "", null),
(17, 0, "", null),
(18, 0, "", null),
(19, 0, "", null),
(20, 0, "", null),
(21, 0, "", null),
(22, 0, "", null),
(23, 0, "", null),
(24, 0, "", null),
(25, 0, "", null),
(26, 0, "", null),
(27, 0, "", null),
(28, 0, "", null),
(29, 0, "", null),
(30, 0, "", null),
(31, 0, "", null),
(32, 0, "", null),
(33, 0, "", null),
(34, 0, "", null),
(35, 0, "", null),
(36, 0, "", null),
(37, 0, "", null),
(38, 0, "", null),
(39, 0, "", null),
(40, 0, "", null),
(41, 0, "", null),
(42, 0, "", null),
(43, 0, "", null),
(44, 0, "", null),
(45, 0, "", null),
(46, 0, "", null),
(47, 0, "", null),
(48, 0, "", null),
(49, 0, "", null),
(50, 0, "", null),
(51, 0, "", null),
(52, 0, "", null),
(53, 0, "", null),
(54, 0, "", null),
(55, 0, "", null),
(56, 0, "", null),
(57, 0, "", null),
(58, 0, "", null),
(59, 0, "", null),
(60, 0, "", null),
(61, 0, "", null),
(62, 0, "", null),
(63, 0, "", null),
(64, 0, "", null),
(65, 0, "", null),
(66, 0, "", null),
(67, 0, "", null),
(68, 0, "", null),
(69, 0, "", null),
(70, 0, "", null),
(71, 0, "", null),
(72, 0, "", null),
(73, 0, "", null),
(74, 0, "", null),
(75, 0, "", null),
(76, 0, "", null),
(77, 0, "", null),
(78, 0, "", null),
(79, 0, "", null),
(80, 0, "", null),
(81, 0, "", null),
(82, 0, "", null),
(83, 0, "", null),
(84, 0, "", null),
(85, 0, "", null),
(86, 0, "", null),
(87, 0, "", null),
(88, 0, "", null),
(89, 0, "", null),
(90, 0, "", null),
(91, 0, "", null),
(92, 0, "", null),
(93, 0, "", null),
(94, 0, "", null),
(95, 0, "", null),
(96, 0, "", null);


CREATE TABLE `team_unphased` (
	`player_id` INT AUTO_INCREMENT NOT NULL,
    `player_name` VARCHAR(20) NOT NULL,
    `tasks_completed` INT,
    PRIMARY KEY(`player_id`)
);

CREATE TABLE `team_unphased_board_state` (
	`task_id` INT AUTO_INCREMENT NOT NULL,
    `task_completion` BOOLEAN,
    `completed_by` VARCHAR(20) DEFAULT "",
    `completed_on` DATETIME DEFAULT NULL,
    PRIMARY KEY(`task_id`)
);

INSERT INTO `team_unphased_board_state` VALUES 
(1, 0, "", null),
(2, 0, "", null),
(3, 0, "", null),
(4, 0, "", null),
(5, 0, "", null),
(6, 0, "", null),
(7, 0, "", null),
(8, 0, "", null),
(9, 0, "", null),
(10, 0, "", null),
(11, 0, "", null),
(12, 0, "", null),
(13, 0, "", null),
(14, 0, "", null),
(15, 0, "", null),
(16, 0, "", null),
(17, 0, "", null),
(18, 0, "", null),
(19, 0, "", null),
(20, 0, "", null),
(21, 0, "", null),
(22, 0, "", null),
(23, 0, "", null),
(24, 0, "", null),
(25, 0, "", null),
(26, 0, "", null),
(27, 0, "", null),
(28, 0, "", null),
(29, 0, "", null),
(30, 0, "", null),
(31, 0, "", null),
(32, 0, "", null),
(33, 0, "", null),
(34, 0, "", null),
(35, 0, "", null),
(36, 0, "", null),
(37, 0, "", null),
(38, 0, "", null),
(39, 0, "", null),
(40, 0, "", null),
(41, 0, "", null),
(42, 0, "", null),
(43, 0, "", null),
(44, 0, "", null),
(45, 0, "", null),
(46, 0, "", null),
(47, 0, "", null),
(48, 0, "", null),
(49, 0, "", null),
(50, 0, "", null),
(51, 0, "", null),
(52, 0, "", null),
(53, 0, "", null),
(54, 0, "", null),
(55, 0, "", null),
(56, 0, "", null),
(57, 0, "", null),
(58, 0, "", null),
(59, 0, "", null),
(60, 0, "", null),
(61, 0, "", null),
(62, 0, "", null),
(63, 0, "", null),
(64, 0, "", null),
(65, 0, "", null),
(66, 0, "", null),
(67, 0, "", null),
(68, 0, "", null),
(69, 0, "", null),
(70, 0, "", null),
(71, 0, "", null),
(72, 0, "", null),
(73, 0, "", null),
(74, 0, "", null),
(75, 0, "", null),
(76, 0, "", null),
(77, 0, "", null),
(78, 0, "", null),
(79, 0, "", null),
(80, 0, "", null),
(81, 0, "", null),
(82, 0, "", null),
(83, 0, "", null),
(84, 0, "", null),
(85, 0, "", null),
(86, 0, "", null),
(87, 0, "", null),
(88, 0, "", null),
(89, 0, "", null),
(90, 0, "", null),
(91, 0, "", null),
(92, 0, "", null),
(93, 0, "", null),
(94, 0, "", null),
(95, 0, "", null),
(96, 0, "", null);


CREATE TABLE `tasks` (
	`task_id` INT AUTO_INCREMENT NOT NULL,
    `point_value` INT NOT NULL,
    `task_name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`task_id`)
);

INSERT INTO `tasks` VALUES
(1,5,"Most cumulative beer brought during all task completions"),
(2,2,"Receive a non-prayer scroll purple unique from Chambers of Xeric (Buckler, DHCB, Dinh's, Ancestral, Dragon Claws, Elder Maul, Kodai, Twisted Bow, Kit, Dust, Pet)"),
(3,3,"Obtain an Enhanced Crystal Weapon Seed"),
(4,2,"Achieve 5,000,000 Woodcutting XP AND obtain a Fox Whistle"),
(5,3,"Obtain all pieces to complete a Voidwaker"),
(6,1,"Obtain a Warped sceptre"),
(7,1,"Achieve 125,000 xp/hr for a minimum of 60 minutes while mining"),
(8,1,"Obtain a Dark Bow"),
(9,1,"Obtain an Ash covered tome from Petrified Pete's Ore Shop"),
(10,3,"Obtain one of three Visages (Skeletal, Wyvern, or Draconic)"),
(11,5,"Last the longest, while still killing the Corrupted Hunleff (Must loot chest after)"),
(12,2,"Receive a purple unique from Theatre of Blood (Avernic defender hilt, Justicar, Rapier, Sanguinesti, Scythe, Kit, Dust, Pet)"),
(13,1,"Alch the purple you received (one time use)"),
(14,2,"Complete Chambers solo in under 17 minutes, trio under 14:30, or any other team size under 12:30."),
(15,3,"Receive an imbued heart, dust battlestaff, mist battlestaff, or eternal gem from a Superior"),
(16,3,"Obtain a drop from the Mega-rare table from a master clue"),
(17,3,"Obtain an Abyssal Lantern and Abyssal Needle"),
(18,2,"Obtain an Occult Necklace"),
(19,1,"Obtain all of the wilderness rings"),
(20,2,"Complete a Grandmaster quest"),
(21,2,"Earn a Fire cape before anyone else"),
(22,5,"Score a goal in gnomeball against an opposing bingo team"),
(23,1,"Obtian a Revenant Weapon (Viggora's Chainmace, Craw's Bow, or Thammaron's Sceptre)"),
(24,2,"Receive a good purple unique from Tombs of Amascut (Masori, Fang, Shadow, Pet)"),
(25,2,"Obtain the following: Bandos Chestplate, Armadyl Chainskirt, Zamorak Spear, Armadyl Crossbow, Zaryte Vambraces. Then wear this outfit and screenshot saying \"I am the God this dungeon was named after.\" (have other weapon in inventory while not wearing)"),
(26,3,"Obtain a Slepey Tabley and any Nightmare Unique (Staff, Inquisitor, Orb, Pet, Jar, Egg)"),
(27,2,"Obtain a Hydra Claw or Hydra Leather"),
(28,2,"Successfully bake a Wild Pie. Ironman style. (Gather all ingredients, and successful process.)"),
(29,1,"Obtain a Pharaoh's Sceptre from Pyramid Plunder"),
(30,1,"Obtain a unique from Zalcano (Crystal tool seed, Zalcano shard, pet, onyx)"),
(31,2,"Least deaths wins. Nominate your Champion. \"PK\" opposing teams while completing ToB. One point goes to the team whos member has the least deaths"),
(32,5,"Achieve the highest level invocation Tombs of Amascut completion in any scale"),
(33,3,"Obtain a Sigil, Jar, or Pet from Corp"),
(34,3,"Obtain any vestige from one of the Desert Treasure II bosses"),
(35,2,"Obtain an Eternal Glory"),
(36,1,"Kill 10 different quest bosses"),
(37,1,"Receive an 84,000 thieving experience drop"),
(38,2,"Complete a heavy ballista"),
(39,1,"Create an Amulet of Torture, Ironman style"),
(40,2,"Obtain Dragon limbs"),
(41,5,"Earn an Infernal cape before anyone else"),
(42,3,"Achieve the most valuable Bounty Hunter PK (cannot be boosted/friends/clan/etc.)"),
(43,1,"Obtain a crystal from Cerberus (Eternal, Pegasian, Primordial)"),
(44,2,"Obtain a non-head unique from Vorkath (Dragonbone necklace, Jar, pet, either visage) (asking about wrath talisman loses your team 1 point)"),
(45,1,"Obtain Bryophyta's Essence"),
(46,2,"Obtain a Nex Unique (Hilt, Vambs, Torva, Horn, Pet) (I will allow vambs if you already got them from the God of the Dungeon tile)"),
(47,1,"Kill Giant Mole 500 times"),
(48,1,"Obtain all four rings from Dagannoth Kings"),
(49,2,"Purchase 10000+ sharks from minnows in a single transaction"),
(50,1,"Catch a Lucky Impling"),
(51,5,"Win a game of Connect-Four against another team's member"),
(52,3,"Earn the title: \"of a Thousand Hunts\". Catch 1000 Salamanders, 1000 Chins, 1000 Implings, and 1000 Herbiboar."),
(53,5,"Have 3 people from your team earn an Infernal cape (if you got a kc during the \"earn a cape before anyone else\" tile, I will count that too)"),
(54,2,"Obtain a fang and a visage from Zulrah"),
(55,1,"Obtain a Granite thing from Grotesque Guardians (except dust)"),
(56,2,"Obtain a double item chest from Barrows, or finish a full set for one brother"),
(57,3,"Receive a Dragon Full Helm as a drop"),
(58,1,"Obtain a Sarachnis cudgel"),
(59,1,"Receive a Blood Shard as a drop (Thieving or Killing Vyrewatch)"),
(60,1,"Obtain an Earth Warrior Champion's Scroll"),
(61,5,"Achieve the largest XP drop out of any other team (Must show up as a single XP drop to count)"),
(62,3,"Best fashionscape (Foki is judge) (Submit all screenshots anonymously from team captain with no identifiable info)"),
(63,3,"Make your Torva bloody. (if you already have blood torva, screenshot new kcs.)"),
(64,1,"Kill the King Black Dragon without wearing or equipping anything"),
(65,2,"Kill all five God Wars bosses in a single inventory without banking or leaving the God Wars Dungeon"),
(66,1,"Obtain an Abyssal Whip"),
(67,1,"Obtain a master wand from the mage training arena"),
(68,5,"Win a game of Castle Wars against another competing team"),
(69,3,"Obtain a Dragon Warhammer"),
(70,3,"Obtain full Virtus"),
(71,1,"Obtain a Skotizo unique (claw, pet, onyx, Jar)"),
(72,2,"Turn Amy into a Sellout. Buy one of everything from the Mahogany Homes Reward Shop"),
(73,1,"Obtain an Unsired"),
(74,1,"Obtain a Trident of the seas, and a Kraken tentacle"),
(75,5,"Achieve the most consecutive LMS wins. (Screenshots of each win with kc is required)"),
(76,1,"Obtain a Venator Shard"),
(77,3,"Complete a deathless, 5-man ToB with a maximum of 1 person from each bingo team"),
(78,1,"Obtain a Kalphite Queen uniqe (Tattered head, Dragon pickaxe, pet, jar, dragon chainbody)"),
(79,1,"Obtain a black mask"),
(80,1,"Create a sword in Giant's Foundry with a score of 69"),
(81,1,"Purchase the full Brimhaven Agility Arena Graceful recolour"),
(82,5,"Most gp earned in 1 hour on a fresh lvl 3 FTP ironman - final screenshot must include time played and be less than 60 mintues"),
(83,3,"Kill Duke Sucellus with the least valuable setup"),
(84,1,"Complete a sled run in Goblin Village with a time of 0:50 or less"),
(85,1,"Obtain a bunch of stuff from Chaos Archeologist. (Rcb, Fedora, Odium Shard, Malediction Shard)"),
(86,1,"Achieve Diamond time for the Earnest the Chicken quest speedrun"),
(87,3,"Equip the highest combined defense and attack bonus out of any team while on Entrana. (Will add up the two highest + bonuses)"),
(88,1,"Kill the bunny in Priffdinas"),
(89,1,"Obtain a full set of Chaos Druid robes"),
(90,1,"Achieve a Hallowed Sepulchre (all 5 floors) time of 6:20 or better"),
(91,1,"Obtain a Clue in a Bottle of every type simultaneously (all five tiers)"),
(92,1,"BONUS: Get a skilling pet"),
(93,1,"BONUS: Get a boss pet"),
(94,1,"BONUS: Get a 99"),
(95,1,"BONUS: PK over 100m to someone not in clan, not in deathmatch. Just a good ol fashioned wildy PK."),
(96,1,"BONUS: Get sasa to say \"I love you\".");